CREATE TABLE IF NOT EXISTS friendships (
  id0 INTEGER NOT NULL,
  id1 INTEGER NOT NULL,
  status INTEGER NOT NULL,
  PRIMARY KEY (id0, id1),
  FOREIGN KEY (id0) REFERENCES users (id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  FOREIGN KEY (id1) REFERENCES users (id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);
